/**
 * Generate `src/components/berlin/data/berlinRoutes.ts` — precomputed route
 * geometry for the itinerary's point-to-point legs (see `utils/daySegments.ts`).
 *
 * Walking legs come from the FOSSGIS OSRM instance (foot profile); transit
 * legs from the Transitous (MOTIS) public API. Both are free, keyless public
 * services — this script runs on demand and the output is committed, so the
 * app itself never calls them.
 *
 * Usage: bun run scripts/generateBerlinRoutes.ts && bun run format
 */
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { DAYS } from '../src/components/berlin/data/berlinItinerary'
import { byId } from '../src/components/berlin/data/berlinPlaces'
import type { BerlinRoute, BerlinRouteLeg } from '../src/components/berlin/data/berlinRouteTypes'
import { daySegments, type DaySegment } from '../src/components/berlin/utils/daySegments'
import { decodePolyline, encodePolyline } from '../src/components/berlin/utils/polyline'

const OSRM_FOOT = 'https://routing.openstreetmap.de/routed-foot/route/v1/foot'
const TRANSITOUS = 'https://api.transitous.org/api/v3/plan'

// Plan transit against the real trip dates (10:00 Berlin = 08:00Z) so
// Transitous uses schedules that actually apply.
const DAY_DATE: Record<string, string> = {
  sun: '2026-07-12',
  mon: '2026-07-13',
  tue: '2026-07-14',
  wed: '2026-07-15',
  thu: '2026-07-16',
  fri: '2026-07-17',
  sat: '2026-07-18',
  flex: '2026-07-15',
}

type LngLat = [number, number]
const r5 = (n: number): number => Math.round(n * 1e5) / 1e5
const round5 = (coords: readonly LngLat[]): LngLat[] => coords.map(([lng, lat]) => [r5(lng), r5(lat)])

type OsrmResponse = {
  code: string
  routes?: {
    distance: number
    duration: number
    geometry: { coordinates: LngLat[] }
    legs: { steps: { name: string; distance: number }[] }[]
  }[]
}

type MotisItinerary = {
  duration: number
  legs: {
    mode: string
    routeShortName?: string
    legGeometry: { points: string; precision?: number }
  }[]
}

type MotisResponse = { itineraries?: MotisItinerary[]; direct?: MotisItinerary[] }

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`)
  return (await res.json()) as T
}

async function walkRoute(seg: DaySegment): Promise<BerlinRoute> {
  const a = byId[seg.fromId]
  const b = byId[seg.toId]
  const url = `${OSRM_FOOT}/${a.lng},${a.lat};${b.lng},${b.lat}?overview=full&geometries=geojson&steps=true`
  const json = await fetchJson<OsrmResponse>(url)
  const route = json.routes?.[0]
  if (json.code !== 'Ok' || !route) throw new Error(`no foot route for ${seg.key}`)
  const streets = route.legs.flatMap((l) => l.steps.map((s) => s.name)).filter(Boolean)
  const via = [...new Set(streets)].slice(0, 4)
  return {
    durationMin: Math.max(1, Math.round(route.duration / 60)),
    distanceM: Math.round(route.distance),
    via: via.length ? via : undefined,
    legs: [{ mode: 'walk', points: encodePolyline(round5(route.geometry.coordinates)) }],
  }
}

async function transitRoute(seg: DaySegment, date: string): Promise<BerlinRoute> {
  const a = byId[seg.fromId]
  const b = byId[seg.toId]
  const url = `${TRANSITOUS}?fromPlace=${a.lat},${a.lng}&toPlace=${b.lat},${b.lng}&time=${date}T08:00:00Z&numItineraries=1`
  const json = await fetchJson<MotisResponse>(url)
  const it = json.itineraries?.[0] ?? json.direct?.[0]
  // Short hops sometimes plan as walk-only; fall back to the foot router.
  if (!it) return walkRoute(seg)
  const legs: BerlinRouteLeg[] = []
  for (const leg of it.legs) {
    const coords = round5(decodePolyline(leg.legGeometry.points, leg.legGeometry.precision ?? 6))
    if (coords.length < 2) continue
    legs.push({
      mode: leg.mode === 'WALK' ? 'walk' : 'transit',
      name: leg.mode === 'WALK' ? undefined : (leg.routeShortName ?? leg.mode),
      points: encodePolyline(coords),
    })
  }
  if (!legs.length) throw new Error(`empty transit route for ${seg.key}`)
  return { durationMin: Math.max(1, Math.round(it.duration / 60)), legs }
}

const routes: Record<string, BerlinRoute> = {}
for (const day of DAYS) {
  for (const seg of daySegments(day)) {
    if (routes[seg.key]) continue
    const route = seg.mode === 'walk' ? await walkRoute(seg) : await transitRoute(seg, DAY_DATE[day.key])
    routes[seg.key] = route
    const lines = route.legs.filter((l) => l.name).map((l) => l.name)
    console.log(
      `${day.key.padEnd(4)} ${seg.key.padEnd(42)} ${seg.mode.padEnd(7)} ~${route.durationMin} min ${lines.join(' → ')}`,
    )
    await new Promise((resolve) => setTimeout(resolve, 500))
  }
}

const outPath = path.join(import.meta.dirname, '../src/components/berlin/data/berlinRoutes.ts')
writeFileSync(
  outPath,
  `/**
 * GENERATED by \`bun run scripts/generateBerlinRoutes.ts\` — do not edit by hand.
 *
 * Precomputed geometry for the itinerary's point-to-point legs: walking routes
 * from OSRM (FOSSGIS foot profile), transit routes from Transitous (MOTIS).
 * Keyed \`fromId->toId\` — see \`utils/daySegments.ts\`.
 */
import type { BerlinRoute } from './berlinRouteTypes'

export const BERLIN_ROUTES: Record<string, BerlinRoute> = ${JSON.stringify(routes, null, 2)}
`,
)
console.log(`\nwrote ${Object.keys(routes).length} routes to ${outPath}`)
